namespace: adammack2007
name: arista_base_config
version: 1.0.0

readme: README.md

authors:
  - Adam Mack - adammack2007@gmail.com
description: Collection of Arista network roles to perform a base configuration of the device.

license:
  - GPL-2.0-or-later

tags: ["arista", "network", "eos"]

repository: https://github.com/AdamMack2007/arista_base_configuration

documentation: https://github.com/AdamMack2007/arista_base_configuration/blob/master/README.md
